### ISSUE TITLE
Shadowlands Upgrade

### ISSUE THREAD

**Issue by powerhandlar** [Naeriam/AlterCurrencies#1]
Shadowland broke this very nice addon, lua error shown with me:
```Message: Interface\AddOns\AlterCurrencies\AlterCurrencies.lua:44: attempt to call global 'GetCurrencyListSize' (a nil value)
Time: Sun Oct 18 07:34:01 2020
Count: 2
Stack: Interface\AddOns\AlterCurrencies\AlterCurrencies.lua:44: attempt to call global 'GetCurrencyListSize' (a nil value)
[string "=[C]"]: in function `GetCurrencyListSize'
[string "@Interface\AddOns\AlterCurrencies\AlterCurrencies.lua"]:44: in function `GetCurrencyAmounts'
[string "@Interface\AddOns\AlterCurrencies\AlterCurrencies.lua"]:90: in function <Interface\AddOns\AlterCurrencies\AlterCurrencies.lua:74>

Locals:

**Comment by Naeriam** [comment]
Hi @powerhandlar

Thank you for realizing and communicating these issues. 
There are indeed issues related to changes in the API in Shadowlands patch.

You have more details in curseforge: 
https://www.curseforge.com/wow/addons/alter-currencies#c10

If you could please confirm that my changes solve the errors, I will close the issue and release a new version.

Ty!

**Comment by powerhandlar** [comment]
Did as requested, yes it does, but still throws an error.

**Comment by Naeriam** [comment]
Thanks @powerhandlar   
I think I have found the problem. I have posted an new response on CuseForge:
https://www.curseforge.com/wow/addons/alter-currencies#c12

**Comment by powerhandlar** [comment]
Great, you did it by that change!
